AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Notifications

  Sample SAM Template for FridgeFinder Notifications Service

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 60
    MemorySize: 256

Parameters:
  Environment:
    Type: String
    Description: Choose between local or AWS
    AllowedValues:
      - local
      - aws
  Stage:
    Type: String
    Description: Choose between dev, staging, prod
    AllowedValues:
      - dev
      - staging
      - prod
  CFMHostedZoneId:
    Type: String
    Description: Grab the HostedZoneId from Route53 console


Resources:
  ApiCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Sub api-${Stage}.communityfridgefinder.com
      DomainValidationOptions:
       - DomainName: !Sub api-${Stage}.communityfridgefinder.com
         HostedZoneId: !Sub ${CFMHostedZoneId}
      ValidationMethod: DNS
  ApiGatewayApi:
      Type: AWS::Serverless::Api
      Properties:
        StageName: !Ref Stage
        # CORS preflight settings from https://vercel.com/guides/how-to-enable-cors
        Cors:
          AllowMethods: "'GET,OPTIONS,PATCH,DELETE,POST,PUT'"
          AllowHeaders: "'X-CSRF-Token, X-Requested-With, Accept, Accept-Version, Content-Length,
            Content-MD5, Content-Type, Date, X-Api-Version'"
          AllowOrigin: "'*'"
          MaxAge: "'86400'"
          AllowCredentials: false
        EndpointConfiguration: REGIONAL
        Domain:
          DomainName: !Sub api-${Stage}.communityfridgefinder.com
          CertificateArn: !Ref ApiCertificate
          Route53:
            HostedZoneName: "communityfridgefinder.com." # NOTE: The period at the end is required
  
  ##########################
  ##   Lambda Functions   ##
  ##########################
  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: functions/hello_world/
      Handler: app.lambda_handler
      Runtime: python3.13
      Architectures:
        - x86_64
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello
            Method: get
            RestApiId:
              Ref: ApiGatewayApi
  
  UserFridgeNotificationsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/fridge_notifications/user
      Handler: app.lambda_handler
      Runtime: python3.13
      FunctionName: !Sub UserFridgeNotificationsFunction${Stage}
      Environment:
        Variables:
          Environment: !Ref Environment
          Stage: !Ref Stage
      Layers:
        - !Ref CommonLayer
      Policies:
        - Version: "2012-10-17"
          Statement:
          - Effect: Allow
            Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
            Resource: arn:aws:logs:*:*:*
          - Effect: Allow
            Action:
            - dynamodb:GetItem
            - dynamodb:PutItem
            Resource: !GetAtt UserFridgeNotificationsTable.Arn
      Events:
        PostUserFridgeNotification:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /v1/users/{user_id}/notifications/{fridge_id}
            Method: post
            RestApiId:
              Ref: ApiGatewayApi
        PutUserFridgeNotification:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /v1/users/{user_id}/notifications/{fridge_id}
            Method: put
            RestApiId:
              Ref: ApiGatewayApi
        GetUserFridgeNotification:
          Type: Api
          Properties:
            Path: /v1/users/{user_id}/notifications/{fridge_id}
            Method: get
            RestApiId:
              Ref: ApiGatewayApi
            RequestParameters:
              - method.request.path.user_id:
                  Required: true
                  Caching: false
              - method.request.path.fridge_id:
                  Required: true
                  Caching: false
  
  GetAllUserFridgeNotificationsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/fridge_notifications/getAllUserNotifications
      Handler: app.lambda_handler
      Runtime: python3.13
      FunctionName: !Sub GetAllUserFridgeNotificationsFunction${Stage}
      Environment:
        Variables:
          Environment: !Ref Environment
          Stage: !Ref Stage
      Layers:
        - !Ref CommonLayer
      Policies:
        - Version: "2012-10-17"
          Statement:
          - Effect: Allow
            Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
            Resource: arn:aws:logs:*:*:*
          - Effect: Allow
            Action:
            - dynamodb:Scan
            Resource: !GetAtt UserFridgeNotificationsTable.Arn
      Events:
        GetAllUserFridgeNotifications:
          Type: Api
          Properties:
            Path: /v1/users/{user_id}/fridges/notifications
            Method: get
            RestApiId:
              Ref: ApiGatewayApi
            RequestParameters:
              - method.request.path.user_id:
                  Required: true
                  Caching: false      

  ##########################
  ##    DynamoDB Tables    ##
  ##########################

  UserFridgeNotificationsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub user_fridge_notifications_${Stage}
      BillingMode: "PAY_PER_REQUEST"
      AttributeDefinitions:
        - AttributeName: "user_id"
          AttributeType: "S"
        - AttributeName: "fridge_id"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "user_id"
          KeyType: "HASH"
        - AttributeName: "fridge_id"
          KeyType: "RANGE"
      GlobalSecondaryIndexes:
        - IndexName: FridgeIndex
          KeySchema:
            - AttributeName: fridge_id
              KeyType: HASH
            - AttributeName: user_id
              KeyType: RANGE
          Projection:
            ProjectionType:All
      #TODO: should we add ProvisionedThroughput?

  ##########################
  ##    CommonLayer    ##
  ##########################
  CommonLayer:
        Type: AWS::Serverless::LayerVersion
        Properties:
            LayerName: !Sub FridgeNotificationsLayer${Stage}
            Description: Dependencies for FridgeFinder Fridge Notifications service
            ContentUri: dependencies/
            CompatibleRuntimes:
              - python3.13
            RetentionPolicy: Delete

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn
